<?php

return [
    'userManagement'          => [
        'title'          => 'User Management',
        'title_singular' => 'User Management',
    ],
    'permission'              => [
        'title'          => 'Permissions',
        'title_singular' => 'Permission',
        'fields'         => [
            'id'                => 'ID',
            'id_helper'         => '',
            'title'             => 'Title',
            'title_helper'      => '',
            'created_at'        => 'Created at',
            'created_at_helper' => '',
            'updated_at'        => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at'        => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],
	  'order'          => [
        'title'          => 'Sales Orders',
        'title_singular' => 'Order',
        'fields'         => [
            'id'                        => 'ID',
            'id_helper'                 => '',
            'sales_team'                => 'Sales Name',
            'sales_team_helper'         => '',
            'order_number'              => 'Order Number',
            'order_number_helper'       => '',
            'order_date'              => 'Ordered Date',
            'po_number'              => 'Selling Price Number',
            'customer_name'             => 'Customer Name',
			'costumer_code'             => 'Customer Code',
            'customer_name_helper'      => '',
            'customer_po'             => 'Customer PO Number',
            'customer_contact'             => 'Customer Contact',
            'sales_order_date'          => 'Sales Order Date',
            'terms_start'          => 'Sales Terms Date Start',
            'terms_end'          => 'Sales Order Terms Date End',
            'type'                      => 'Type',
            'status'                      => 'Status',
            'type_helper'               => '',
            'bill_to'                   => 'Bill To',
            'bill_to_helper'            => '',
            'customer_currency'         => 'Customer Currency',
            'customer_currency_helper'  => '',
            'ship_to'                   => 'Ship To',
            'ship_to_helper'            => '',
            'price_list'                => 'Price List',
            'price_list_helper'         => '',
            'booking_code'              => 'Booking Code',
            'booking_code_helper'       => '',
            'terms'                     => 'Terms',
            'terms_helper'       => '',
            'weight'              => 'Weight / Volume',
            'weight_helper'       => '',
            'customer_email'            => 'Customer Email',
            'customer_email_helper'     => '',
            'products'                  => 'Products',
            'products_helper'           => '',
            'created_at'                => 'Created at',
            'created_at_helper'         => '',
            'updated_at'                => 'Updated at',
            'updated_at_helper'         => '',
            'deleted_at'                => 'Deleted at',
            'deleted_at_helper'         => '',
        ],
    ],
    'role'                    => [
        'title'          => 'Roles',
        'title_singular' => 'Role',
        'fields'         => [
            'id'                 => 'ID',
            'id_helper'          => '',
            'title'              => 'Title',
            'title_helper'       => '',
            'permissions'        => 'Permissions',
            'permissions_helper' => '',
            'created_at'         => 'Created at',
            'created_at_helper'  => '',
            'updated_at'         => 'Updated at',
            'updated_at_helper'  => '',
            'deleted_at'         => 'Deleted at',
            'deleted_at_helper'  => '',
        ],
    ],
    'user'                    => [
        'title'          => 'Users',
        'title_singular' => 'User',
        'fields'         => [
            'id'                       => 'ID',
            'id_helper'                => '',
            'name'                     => 'Name',
            'name_helper'              => '',
            'email'                    => 'Email',
            'email_helper'             => '',
            'email_verified_at'        => 'Email verified at',
            'email_verified_at_helper' => '',
            'password'                 => 'Password',
            'password_helper'          => '',
            'roles'                    => 'Roles',
            'roles_helper'             => '',
            'remember_token'           => 'Remember Token',
            'remember_token_helper'    => '',
            'created_at'               => 'Created at',
            'created_at_helper'        => '',
            'updated_at'               => 'Updated at',
            'updated_at_helper'        => '',
            'deleted_at'               => 'Deleted at',
            'deleted_at_helper'        => '',
        ],
    ],
    'clientManagementSetting' => [
        'title'          => 'Settings',
        'title_singular' => 'Settings',
    ],
    'currency'                => [
        'title'          => 'Currencies',
        'title_singular' => 'Currency',
        'fields'         => [
            'id'                   => 'ID',
            'id_helper'            => '',
            'name'                 => 'Name',
            'name_helper'          => '',
            'code'                 => 'Currency code',
            'code_helper'          => '',
            'main_currency'        => 'Main currency',
            'main_currency_helper' => '',
            'created_at'           => 'Created at',
            'created_at_helper'    => '',
            'updated_at'           => 'Updated At',
            'updated_at_helper'    => '',
            'deleted_at'           => 'Deleted At',
            'deleted_at_helper'    => '',
        ],
    ],
    'transactionType'         => [
        'title'          => 'Transaction types',
        'title_singular' => 'Transaction type',
        'fields'         => [
            'id'                => 'ID',
            'id_helper'         => '',
            'name'              => 'Name',
            'name_helper'       => '',
            'created_at'        => 'Created at',
            'created_at_helper' => '',
            'updated_at'        => 'Updated At',
            'updated_at_helper' => '',
            'deleted_at'        => 'Deleted At',
            'deleted_at_helper' => '',
        ],
    ],
    'incomeSource'            => [
        'title'          => 'Income sources',
        'title_singular' => 'Income source',
        'fields'         => [
            'id'                 => 'ID',
            'id_helper'          => '',
            'name'               => 'Name',
            'name_helper'        => '',
            'fee_percent'        => 'Fee Percent',
            'fee_percent_helper' => '',
            'created_at'         => 'Created at',
            'created_at_helper'  => '',
            'updated_at'         => 'Updated At',
            'updated_at_helper'  => '',
            'deleted_at'         => 'Deleted At',
            'deleted_at_helper'  => '',
        ],
    ],
    'clientStatus'            => [
        'title'          => 'Client statuses',
        'title_singular' => 'Client status',
        'fields'         => [
            'id'                => 'ID',
            'id_helper'         => '',
            'name'              => 'Name',
            'name_helper'       => '',
            'created_at'        => 'Created at',
            'created_at_helper' => '',
            'updated_at'        => 'Updated At',
            'updated_at_helper' => '',
            'deleted_at'        => 'Deleted At',
            'deleted_at_helper' => '',
        ],
    ],
    'projectStatus'           => [
        'title'          => 'Project statuses',
        'title_singular' => 'Project status',
        'fields'         => [
            'id'                => 'ID',
            'id_helper'         => '',
            'name'              => 'Name',
            'name_helper'       => '',
            'created_at'        => 'Created at',
            'created_at_helper' => '',
            'updated_at'        => 'Updated At',
            'updated_at_helper' => '',
            'deleted_at'        => 'Deleted At',
            'deleted_at_helper' => '',
        ],
    ],
    'clientManagement'        => [
        'title'          => 'Client management',
        'title_singular' => 'Client management',
    ],
    'client'                  => [
        'title'          => 'Clients',
        'title_singular' => 'Client',
        'fields'         => [
            'id'                => 'ID',
            'id_helper'         => '',
            'first_name'        => 'First name',
            'first_name_helper' => '',
            'last_name'         => 'Last name',
            'last_name_helper'  => '',
            'company'           => 'Company',
            'company_helper'    => '',
            'email'             => 'Email',
            'email_helper'      => '',
            'phone'             => 'Phone',
            'phone_helper'      => '',
            'website'           => 'Website',
            'website_helper'    => '',
            'skype'             => 'Skype',
            'skype_helper'      => '',
            'country'           => 'Country',
            'country_helper'    => '',
            'status'            => 'Client Status',
            'status_helper'     => '',
            'created_at'        => 'Created at',
            'created_at_helper' => '',
            'updated_at'        => 'Updated At',
            'updated_at_helper' => '',
            'deleted_at'        => 'Deleted At',
            'deleted_at_helper' => '',
        ],
    ],
    'project'                 => [
        'title'          => 'Projects',
        'title_singular' => 'Project',
        'fields'         => [
            'id'                 => 'ID',
            'id_helper'          => '',
            'name'               => 'Name',
            'name_helper'        => '',
            'client'             => 'Client',
            'client_helper'      => '',
            'description'        => 'Description',
            'description_helper' => '',
            'start_date'         => 'Start Date',
            'start_date_helper'  => '',
            'budget'             => 'Budget',
            'budget_helper'      => '',
            'status'             => 'Project Status',
            'status_helper'      => '',
            'created_at'         => 'Created at',
            'created_at_helper'  => '',
            'updated_at'         => 'Updated At',
            'updated_at_helper'  => '',
            'deleted_at'         => 'Deleted At',
            'deleted_at_helper'  => '',
        ],
    ],
    'note'                    => [
        'title'          => 'Notes',
        'title_singular' => 'Note',
        'fields'         => [
            'id'                => 'ID',
            'id_helper'         => '',
            'project'           => 'Project',
            'project_helper'    => '',
            'note_text'         => 'Note Text',
            'note_text_helper'  => '',
            'created_at'        => 'Created at',
            'created_at_helper' => '',
            'updated_at'        => 'Updated At',
            'updated_at_helper' => '',
            'deleted_at'        => 'Deleted At',
            'deleted_at_helper' => '',
        ],
    ],
    'document'                => [
        'title'          => 'Documents',
        'title_singular' => 'Document',
        'fields'         => [
            'id'                   => 'ID',
            'id_helper'            => '',
            'project'              => 'Project',
            'project_helper'       => '',
            'document_file'        => 'File',
            'document_file_helper' => '',
            'name'                 => 'Document Name',
            'name_helper'          => '',
            'description'          => 'Description',
            'description_helper'   => '',
            'created_at'           => 'Created at',
            'created_at_helper'    => '',
            'updated_at'           => 'Updated At',
            'updated_at_helper'    => '',
            'deleted_at'           => 'Deleted At',
            'deleted_at_helper'    => '',
        ],
    ],
    'customer'                => [
        'title'          => 'Customer',
        'edit'          => 'Edit Customer',
        'title_sidebar'          => 'Customer Site',
        'title_singular' => 'Customer',
        'fields'         => [
            'cust_party_code'  => 'Customer Code',
            'purpose_date' => 'Purpose Date',
            'party_name' => 'Customer Name',
            'address1' => 'Address',
            'address2' => 'Address Alternate',
            'address3' => 'Address Shipment',
            'city' => 'City',
            'province' => 'Province',
            'district' => 'District (Kecamatan)',
            'neighborhoods' => 'Neighbor Hoods (Kelurahan)',
            'country' => 'Country',
            'phone' => 'Phone',
            'mobile' => 'Mobile Phone',
            'email' => 'Email',
            'postal_code' => 'Postal Code',
            'site_code' => 'Site Code',
            'sales_tax_code' => 'Tax Code',
            'currency_code' => 'Currency Code',
            'status' => 'Status',
            'title' => 'Title',
            'customer_type' => 'Customer Type',
            'type' => 'Contact Type',
            'job_position' => 'Job Position',
            'pic'=> 'Person In Charge',
            'block'=> 'Block',
            'number'=> 'Number',
            'rt'=> 'RT',
            'rw'=> 'RW',
            'pic'=> 'Person In Charge',
            'npwp'=> 'NPWP',
            'phone_site' => 'Phone',
            'mobile_site' => 'Mobile Phone',
            'email_site' => 'Email',
            'postal_code_site' => 'Postal Code',
            'address1_site' => 'Address',
            'address2_site' => 'Address Alternate',
            'address3_site' => 'Address Shipment',


        ],
    ],
    'site'                => [
        'title'          => 'Site',
        'edit'          => 'Edit Site',
        'title_sidebar'          => 'Site',
        'title_singular' => 'Site',
        'fields'         => [
            'vendor_code'          => 'Vendor Code',
            'code'            	   => 'Site Code',
            'name'                 => 'Name',
            'address1'         	   => 'Address1',
            'address2'         	   => 'Address2',
            'address3'         	   => 'Address3',
            'city'                 => 'City ',
            'province'             => 'Province',
            'country'              => 'Country',
            'postal_code'          => 'Postal Code',
            'type'             	   => 'Type',
            'email'                => 'Email',
            'phone'                => 'Phone',
            'bank_number'          => 'Bank',
            'id_helper'            => '',
        ],
    ],
    'pricelist'                => [
        'title'          => 'Price List',
        'title'          => 'Price List',
        'fields'         => [
            'price_list_name'=> 'Price List For',
            'products'=> 'Products',
            'description'=> 'Description',
            'effective_date'=> 'Effective Date',
            'currency'=> 'Currency',
            'location_id'=> 'Location ID',
            'created_by'=> 'Document Created By',
            'flag_status'=> 'Status',
            // list
            'header_id'=> 'Status',
            'line_id'=> 'Status',
            'inventory_item_id'=> 'Product ID',
            'user_item_description'=> 'User Item Description',
            'uom'=> 'Unit of Measure',
            'unit_price'=> 'Unit Price',
            'discount'=> 'Discount',
            'packing_type'=> 'Packing Type',
            'effective_from'=> 'Effective From',
            'effective_to'=> 'Effective To',
        ],
    ],
    'transaction'             => [
        'title'          => 'Transactions',
        'title_singular' => 'Transaction',
        'fields'         => [
            'id'                      => 'ID',
            'id_helper'               => '',
            'project'                 => 'Project',
            'project_helper'          => '',
            'transaction_type'        => 'Transaction Type',
            'transaction_type_helper' => '',
            'income_source'           => 'Income Source',
            'income_source_helper'    => '',
            'amount'                  => 'Amount',
            'amount_helper'           => '',
            'currency'                => 'Currency',
            'currency_helper'         => '',
            'transaction_date'        => 'Transaction Date',
            'transaction_date_helper' => '',
            'name'                    => 'Name',
            'name_helper'             => '',
            'description'             => 'Description',
            'description_helper'      => '',
            'created_at'              => 'Created at',
            'created_at_helper'       => '',
            'updated_at'              => 'Updated At',
            'updated_at_helper'       => '',
            'deleted_at'              => 'Deleted At',
            'deleted_at_helper'       => '',
        ],
    ],
    'clientReport'            => [
        'title'          => 'Reports',
        'title_singular' => 'Report',
        'reports'        => [
            'month'       => 'Month',
            'income'      => 'Income',
            'expenses'    => 'Expenses',
            'fees'        => 'Fees',
            'total'       => 'Total',
            'allProjects' => 'All projects',
        ],
    ],
    'OrderManagement'            => [
        'title'          => 'Order Management',
        'title_singular' => 'Sales Order',
        'order_organizer' => 'Order Organizer',
        'shipping'        => 'Shipping',
        'quick_ship'        => 'Quick Ship',
        'price_list'        => 'Price List',
        'customer'        => 'Customer',
        'post_invoic'        => 'Auto Invoice',
        'reports'        => [
            'month'       => 'Month',
            'income'      => 'Income',
            'expenses'    => 'Expenses',
            'fees'        => 'Fees',
            'total'       => 'Total',
            'allProjects' => 'All projects',
        ],
        'field' =>[
            'editsalesorder'=>'Edit Sales Order',
            'sales'=>'Sales',
            'pricelistdetail'=>'Price List Detail',
            'shipping'=>'Shipping',
            'action'=>'Action',
            'copyline'=>'Copy Line',
            'multipledelete'=>'Multiple Delete',
            'splitline'=>'Split Line',
            'line'=>'Line',
            'pricelist'=>'Price List',
            'productname'=>'Product Name',
            'shipmentschedule'=>'Shipment Schedule',
            'qty'=>'Qty',
            'uom'=>'UOM',
            'price'=>'Price',
            'tax'=>'Tax',
            'disc'=>'Disc.%',
            'subtotal'=>'Sub.Total',
            'addrow'=>'Add Row',
            'document'=>'Document',
            'price'=>'Price',
            'effectivedate'=>'Effective Date',
            'subinv'=>'Sub Inventory',
            'packingstyle'=>'Packing Style',
            'status'=>'Status',
            'level'=>'Level',
            'taxamount'=>'Tax (Amount)',
            'total'=>'Total',
            'reset'=>'Reset',
            'salesreturn'=>'Sales Return',
            'productname'=>'Product Name',
            'return'=>'Return',
            'price'=>'Price',
            'ordernumber'=>'Order Number',
            'shippinginv'=>'Shipping Inventory',
            'shippingschedule'=>'Shipping Schedule',
            'type'=>'Type',
            'submmitline'=>'Submit Line',
            'id'=>'ID',
            'headerid'=>'Header ID',
            'lineid'=>'Line ID',
            'items'=>'Items',
            'add'=>'Add',
            'copyline'=>'Copy Line',
            'splitline'=>'Split Line',
            'itemdesc'=>'Item Description',
        ],
    ],

    'inventoryAdmin'            => [
        'item_master'     => 'Item Master',
        'org_item'        => 'Organization Item',
        'item_cost'       => 'Item Cost',
    ],
    'itemMaster'            => [
       'org_item'        => 'Organization Item',
       'item_master'     => 'Item Master',
       'title_singular'  => 'Item Master',
       'fields'         => [
           'item_code'     => 'Item Code',
           'attribute'     => 'Attribute',
           'id'     => 'ID',
           'item_helper'     => '',
           'description'     => 'Description',
           'uom'             => 'Primary UOM',
           'Uom'             => 'UOM',
           'item'             => 'Item',
           'suom'            => 'Secondary UOM',
           'status'          => 'Item Status',
           'item_type'       => 'Item Type',
           'img'       => 'Add Photo',
           'type'       	  => 'Type',
           'buyer'           => 'Buyer',
           'planner'         => 'Planner',
           'purchaseItem'    => 'Purchasing',
           'makeOrbuy'       =>'Source',
           'barcode'         =>'Barcode',
           'brand'           =>'Brand',
           'note'            =>'Internal Notes',
           'asset'           =>'Asset Flag',
           'category'        =>'Category',
           'subcat'          =>'Sub Category',
           'weight'          =>'Weight',
           'height'          =>'Height',
           'volume'          =>'Volume',
           'hscode'          =>'HS Code',
           'lta'             =>'Preprocess',
           'ltp'             =>'Process',
           'packingqty'      =>'Quantity Packing',
           'itemcost'        =>'Item Cost',
           'bomflag'         =>'BOM Flag',
           'fixloc'         =>'Location',
           'sub'             =>'Subinventory',
           'subre'           =>'Receiving Inventory',
           'subre'           =>'Receiving Inventory',
           'subshi'          =>'Shipping Inventory',
           'payable'         =>'Payable ',
           'receivable'      =>'Receivable ',
           'usage'           =>'COGS ',
           'salescc'         =>'Sales ',
           'other'           =>'Other ',
           'inventory'       =>'Inventory ',
           'account'         =>'Account',
           'location'        =>'Location',
           'creation_date'   =>'Creation Date',
           'createdat'  	  =>'Created_at',
           'updatedat'  	  =>'Updated_at',
           'created_by'      =>'Created By',
           'updated_at'      =>'Updated Date',
           'action'          =>'Action',
           'ref'        =>'Reference Items',
           'id_helper'       => '',
       ],
   ],
	'purchaseOrder'            => [
        'item_master'            => 'Item Master',
        'org_item'               => 'Organization Item',
        'title_singular'         => 'Purchase Order',
        'quotation'              => 'Quotation',
        'pr'                     => 'Purchase Requisition',
        'po'                     => 'Purchase Order',
        'autoCreate'             => 'Auto Create',
        'receive'                => 'Receiving',
        'return'                 => 'Return',
        'supplier'               => 'Supplier',
        'supplier_code'               => 'Supplier Code',
        'report'                 => 'Purchase Report',
        'fields'         => [
            'item_code'     => 'Item Code',
            'description'     => 'Description',
            'uom'             => 'Primary UOM',
            'suom'           => 'Secondary UOM',
            'location'        =>'Location',
			'customer_code'        =>'Customer Code',
            'status'        =>'Status',
            'buyer'        =>'Buyer',
            'rate_date'        =>'Rate_Date',
            'ref'          =>'Reference Items',
            'id_helper'       => '',
        ],
    ],
    'order'          => [
        'title'          => 'Sales Orders',
        'title_singular' => 'Order',
        'fields'         => [
            'id'                        => 'ID',
            'id_helper'                 => '',
            'sales_team'                => 'Sales Name',
            'sales_team_helper'         => '',
            'order_number'              => 'Order Number',
            'order_number_helper'       => '',
            'order_date'              => 'Ordered Date',
            'po_number'              => 'Selling Price Number',
            'customer_name'             => 'Customer Name',
            'customer_name_helper'      => '',
            'customer_po'             => 'Customer PO Number',
            'customer_contact'             => 'Customer Contact',
            'sales_order_date'          => 'Sales Order Date',
            'terms_start'          => 'Sales Terms Date Start',
            'terms_end'          => 'Sales Order Terms Date End',
            'type'                      => 'Type',
            'status'                      => 'Status',
            'type_helper'               => '',
            'bill_to'                   => 'Bill To',
            'bill_to_helper'            => '',
            'customer_currency'         => 'Customer Currency',
            'customer_currency_helper'  => '',
            'ship_to'                   => 'Ship To',
            'ship_to_helper'            => '',
            'price_list'                => 'Price List',
            'price_list_helper'         => '',
            'booking_code'              => 'Booking Code',
            'booking_code_helper'       => '',
            'terms'                     => 'Terms',
            'terms_helper'       => '',
            'weight'              => 'Weight / Volume',
            'weight_helper'       => '',
            'customer_email'            => 'Customer Email',
            'customer_email_helper'     => '',
            'products'                  => 'Products',
            'products_helper'           => '',
            'created_at'                => 'Created at',
            'created_at_helper'         => '',
            'updated_at'                => 'Updated at',
            'updated_at_helper'         => '',
            'deleted_at'                => 'Deleted at',
            'deleted_at_helper'         => '',
        ],
    ],
    'quotation'          => [
        'title'          => 'Quotation',
        'title_singular' => 'Quotation',
        'fields'         => [
            'id'                    => 'ID',
            'number'                => 'Number',
            'price'                => 'price',
            'id_helper'             => '',
            'supplier'              => 'Supplier',
            'start_date'              => 'From ',
            'end_date'              => 'To',
            'status'              => 'Status',
            'customer_name_helper'  => '',
            'effective_date'        => 'Effective Date',
            'customer_email_helper' => '',
            'site'                  => 'Site',
            'products_helper'       => '',
            'created_at'            => 'Created at',
            'created_at_helper'     => '',
            'updated_at'            => 'Updated at',
            'updated_at_helper'     => '',
            'deleted_at'            => 'Deleted at',
            'deleted_at_helper'     => '',
            'currency'              => 'Currency',
        ],
    ],
    'vendor'          => [
        'title'          => 'Vendor',
        'title_singular' => 'Vendor',
        'fields'         => [
            'vendor_code'                => 'Code',
            'vendor_name'                => 'Name',
            'address1'                   => 'Address1',
            'address2'                   => 'Address2',
            'city'                       => 'City',
            'province'                   => 'Province',
            'country'                    => 'Country',
            'currency'                   => 'Currency',
            'loc'                        => 'Local',
            'phone'                      => 'Telp',
            'email'                      => 'Email',
            'tax'                        => 'Tax',
            'bank'                       => 'Bank Number',
            'terms'                      => 'Terms',
            'bank_number'                => 'Bank',
            'tax_number'                => 'Tax Num',
            'id_helper'             => '',
        ],
    ],
    'category'=>[
        'title_singular'=>'Category',
        'fields'=>[
            'description'=>'Description',
            'invcode'=>'Invoice',
            'paycode'=>'Paycode',
            'salescode'=>'Sales Code',
            'cogscode'=>'Cogs Code',
            'reccode'=>'Rec Code',
            'code'=>'Code',
            'name'=>'Name',
            'note'=>'Note',

        ]
    ],
    // delivey --Heryy-- updateed at --21-06-2022--
    'Delivery'              => [
        'title'             => 'Delivery',
        'title_singular'    => 'Delivery',
        'fields'            => [
            'deliveryform'  => 'Delivery Number',
            'deliveryto'    => 'Delivery To',
            'fullfillment'  => 'Fullfillment',
            'sj'            => 'Surat Jalan',
            'sjto'          => 'Surat Jalan To',
            'pjg'           => 'Length (m)',
            'lbr'           => 'Width (m)',
            'brt'           => 'Net Weight',
            'gsm'           => 'GSM / Ketebalan',
            'sub'           => 'Sub Inventory',
            'ship'          =>'Ship Confirm',
            'back'          =>'Back All',
            'actual'        =>'Actual Date',
            'acepdet'       =>'Accept Date',
            'orderletter'   =>'Order Letter',
            'customername'  =>'Customer Name',
            'customershipto'=>'Customer Ship To',
            'currency'      =>'Currency',
            'createdby'     =>'Created By',
            'actualdate'    =>'Actual Date',
            'create'        =>'Create',
            'term'          =>'Term',
            'pickrelease'   =>'Launch Pick Release',
            'shipconfirm'   =>'Ship Confirm',
            'deliveryterm'  =>'Delivery Term',
            'shihpmethodcode'   =>'Ship Method Code',
            'fobcode'           =>'Fob Code',
            'addterm'           =>'Add Term',
            'addweight'         =>'Add Weight',
            'detail'            =>'Detail',
            'status'            =>'Status',
        ],
        'table'             => [
            'no_barang'     => 'Order Letter No',
            'cname'         => 'Customer Name',
            'desc_barang'   => 'Item Description',
            'shipto'        => 'Customer Shipto',
            'note'          => 'Note',
            'satuan'        => 'Weight',
            'job'           => 'Job',
            'sj'            => 'Surat Jalan',
            'status'        => 'Status',
            'curenci'       => 'Currency',
            'ft'            => 'Freight',
            'dt'            => 'Delivery Date',
            'inv'           => 'Inventory',
            'qty'           => 'Qty',
            'line'          => 'Line',
        ],
        'button'            => [
            'detail'        => 'Detail',
            'disc'          => 'Discount',
            'hapus'         => 'Hapus Baris',
            'rekam'         => 'Rekam Ulang',
            'buka'          => 'Buka Ulang',
            'stok_list'     => 'Stock List',
            'batal'         => 'Batal',
            'confirm'       => 'Confirm Delivery',
            'reset'         => 'Reset',
        ],
        'modal'             => [
            'confirm'       => 'Confirm Delivery',
            'deliverynumb'  => 'Delivery Number',
            'conf'          => 'Confirm',
            'deliveryterm'  => 'Delivery Term',
            'shipmethodcode'=> 'Ship Method Code',
            'fobcode'       => 'Fob Code',
            'addweight'     => 'Add Weight',
        ],

    ],

    // shiping --Heryy-- updateed at --21-06-2022--
	'shiping'               => [
        'title'             => 'Shipping',
        'title_singular'    => 'Shipping',
        'title_modal'       => 'Quick Ship',
        'fields'            => [
            'id'                => 'ID',
            'customer_name'     => 'Customer Name',
            'invoice_no'        => 'Surat Jalan',
            'order_letter_no'   => 'Delivery Number',
            'invoice_date'      => 'Delivery Date',
            'status'            => 'Status',
            'currency'          => 'Currency',
            'customer_shipto'   => 'Customer Ship to',
            'note'              => 'Note',
            'freight_term'      => 'Freight Term',
            'gross_weight'      => 'Gross Weight',
            'do'                => 'DO',
            'cash'              => 'Cash',
            'total_lines'       => 'Total Lines',
            'qty_perpacking'    => 'Qty Perpacking',
            'total_gross'       => 'Total Gross',
            'delivery_date'     => 'Delivery Date',
            'salesman'          => 'Salesman',
            'term_of_payment'   => 'Term of Payment',
            'memo'              => 'Memo of Credit / Debit',
            'print'             => 'Print',
        ],
        'table'                 => [
            'id'                => 'ID',
            'sn'                => 'Sales Number',
            'item_no'           => 'Item No',
            'item_desc'         => 'Item Description',
            'delivered'         => 'Delivered',
            'ordered'           => 'Ordered',
            'request_qty'       => 'Requested Quantity',
            'uom'               => 'UOM',
            'gross_weight'      => 'Gross Weight',
            'total'             => 'Total',
            'custpo'             => 'Customer PO',
            'unitprice'             => 'Price',
            'subinventory'             => 'Subinventory',
        ],
        'modaltable'            => [
            'id'                => 'ID',
            'sales_order'       => 'Customer Code',
            'line'              => 'Line',
            'cs'                => 'Customer Name',
            'cpo'               => 'Customer PO',
            'item'              => 'Item Code',
            'iddev'             => 'ID',
            'req_qty'           => 'Surat Jalan',
            'qty'               => 'QTY',
            'line_status'       => 'Shipment Date',
            'next_step'         => 'Next Step',
            'note'              => 'Note',
            'curenci'           => 'Currency',
            'ft'                => 'Freight',
            'weight'            => 'Weight',
            'sonumb'            => 'Order Number',
            'ponumb'            => 'PO Number',
            'addnewitemheader'  => 'Add New Shipment',
            'additemheader'     => 'Add Item Shipment',
            'additem'           => 'Add Item',
            'deleteitem'        => 'Delete Item',
            'areyousure'        => 'Are you sure want to delete this row ?',
            'yes'               => 'Yes',
            'no'                => 'No',
            'ln'                => 'Line',
        ],

        'button'                => [
            'detail'            => 'Detail',
            'disc'              => 'Discount',
            'delete_row'        => 'Delete Row',
            'add_record'        => 'Add Shipping',
            'add_new'           => 'Add New Shipping',
            'add_item'          => 'Add Item Shipping',
            'open_rec'          => 'Open Record',
            'stock_list'        => 'Stock List',
            'cancel'            => 'Cancel',
            'save_draft'        => 'Save Draft',
            'save'              => 'Save',
            'search'            => 'Search',
            'search'            => 'Search',
        ],
        'modal'                 => [
            'id'                => 'ID',
            'billto'            => 'Bill To',
            'shipto'            => 'Ship To',
            'order_from'        => 'Order From',
            'order_to'          => 'Order To',
            'item_from'         => 'Item From',
            'item_to'           => 'To',
        ],


    ],
    'Invoice'            => [
        'title'          => 'Invoice',
        'order_organizer' => 'Order Organizer',

        'field'         => [
            'id'                => 'ID',
            'nama_pelanggan'    => 'Nama Pelanggan',
            'no_faktur'         => 'No Faktur',
            'nomor_so'          => 'Nomor SO',
            'tanggal_faktur'    => 'Tanggal Faktur',
            'proyek'            => 'Proyek',
            'mata_uang'         => 'Mata Uang',
            'jasa'              => 'Jasa',
            'keluar_dari_gudang'=> 'Keluar Dari Gudang',
            'ket'               => 'Keterangan',
            'dep'               => 'Department',
            'tunai'             => 'Tunai',
            'biayalain'         => 'Biaya Biaya Lain',
            'disc_fin'          => 'Discount Final',
            'tot'               => 'Total Setelah Discount',
            'tgl_peng'          => 'Tanggal Pengiriman',
            'sales'             => 'Salesman',
            'tot_paj'           => 'Total Pajak',
        ],
        'table'         => [
            'id'        => 'ID',
            'no_barang' => 'No Barang',
            'deskbar'   => 'Deskripsi Barang',
            'dikirim'   => 'Dikirim',
            'diorder'   => 'Diorder',
            'satuan'    => 'Satuan',
            'harga'     => 'Harga',
            'disc'      => 'Disc',
            'total'     => 'Total',
            'pjk'       => 'PJK',
            'job'       => 'JOB',
        ],
        'button'         => [
            'rinci' => 'Rincian',
            'biaya' => 'Biaya Biaya Lain',
            'pajak' => 'Pajak',
            'disc'  => 'Diskon',
            'info'  => 'Informasi Pengiriman',
            'multi' => 'Multi Delivery Order',
        ],
    ],
    'salesreturn'=>[
        'title'     =>'Sales Return',
        'field'     =>[
            'id'    =>'ID',
        ],
    ],
    // added by shindi - 27/04/2022

	'coa'          => [
        'title'          => 'Chart Of Account',
        'title_singular' => 'Chart Of Account',
        'fields'         => [
            'code'            	   => 'Account Code',
            'name'                 => 'Account Name',
            'parent'               => 'Parent Code',
            'description'          => 'Description',
            'type'                 => 'Type ',
            'level'                => 'Level',
            'id_helper'            => '',
            'group'         	   => 'Group',
        ],
    ],
	'autocreate'          => [
        'title'          => 'Auto Create',
        'title_singular' => 'Auto Create',
        'fields'         => [
            'vendor'               => 'Vendor',
            'prno'                 => 'PR Number',
            'item'                 => 'Item Number',
            'quotation'            => 'Quotation',
            'description'          => 'Description',
            'ponum'                => 'Purchase Number',
            'site'       	       => 'Vendor Site',
            'rate_date'       	   => 'Rate Date',
            'currency'       	   => 'Currency',
            'org'       		   => 'Organization',
            'type'                 => 'Type ',
            'level'                => 'Level',
            'id_helper'            => '',
            'group'         	   => 'Group',
            'requested'            => 'Requested By',
        ],
    ],
	  'terms'         => [
        'title'         => 'Global Terms',
        'title_singular' => 'Global Terms',
        'fields'        => [
            'id'                   => 'ID',
            'term_category'        => 'Term Category',
            'term_code'            => 'Term Code',
            'terms_name'           => 'Terms Name',
            'attribute1'           => 'Attribute',
            'created_at'            => 'Created At',
            'updated_at'            => 'Updated at',
            'deleted_at'            => 'Deleted at',
        ],
    ],
	'rcv'                   => [
        'title'             => 'Receive',
        'title_singular'    => 'Receive',
        'fields'            => [
            'id'                   => 'ID',
            'transactiondate'      => 'Transaction Date',
            'grn'                  => 'Good Receipt Note',
            'grnno'                => 'GRN',
            'line'                 => 'Line ID',
            'grnfrom'              => 'GRN From',
            'grnto'                => 'To',
            'packingslip'          => 'Packing Slip',
            'bill'                 => 'Bill No.',
            'received'             => 'Received By',
            'aju'                  => 'Aju',
            'freight'              => 'Freight',
            'container'            => 'Containers',
            'comments'             => 'Notes',
            'supplier'             => 'Supplier',
            'orderno'              => 'Order No.',
            'orderto'              => 'To',
            'item'                 => 'Item',
            'product'              => 'Product',
            'qty'                  => 'QTY',
            'price'                => 'Unit Price',
            'receivedqty'          => 'Received QTY',
            'transactiontype'      => 'Transaction Type',
            'attribute1'           => 'Attribute',
            'created_at'           => 'Created At',
            'updated_at'           => 'Updated at',
            'deleted_at'           => 'Deleted at',
            'action'               => 'Action',
            'customerreceive'      => 'Customer Receive',
            'ordernumber'          => 'Order Number',
            'qty'                  => 'Qty',
            'uom'                  => 'UOM',
            'purchaseorder'        => 'Purchase Item',
            'price'                => 'Price',
            'total'                => 'Total',
            'customerreceive'      => 'Customer Receive',
            'suplierreceive'       => 'Suplier Receive',
        ],
        'customer'                 => [
            'cust'                 => 'Customer',
            'so'                   => 'Sales Number',
        ]
    ],
    'return'                => [
        'title'             => 'Return',
        'title_singular'    => 'Return',
        'fields'            => [
            'id'                   => 'ID',
            'transactiondate'      => 'Transaction Date',
            'grn'                  => 'Good Receipt Note',
            'grnno'                => 'GRN',
            'packingslip'          => 'Packing Slip',
            'bill'                 => 'Bill No.',
            'received'             => 'Received By',
            'freight'              => 'Freight',
            'container'            => 'Containers',
            'comments'             => 'Notes',
            'supplier'             => 'Supplier',
            'orderno'              => 'Order No.',
            'item'                 => 'Item',
            'product'              => 'Product',
            'qty'                  => 'QTY',
            'price'                => 'Unit Price',
            'returnedqty'          => 'Return QTY',
            'transactiontype'      => 'Transaction Type',
            'attribute1'           => 'Attribute',
            'created_at'           => 'Created At',
            'updated_at'           => 'Updated at',
            'deleted_at'           => 'Deleted at',

        ],
    ],
	  'subInventory'         => [
        'title'         => 'Sub Inventory',
        'title_singular' => 'Sub Inventory',
        'fields'        => [
            'id'                    => 'ID',
            'sub_inventory_name'    => 'Sub Inventory Name',
            'description'           => 'Description',
            'locator_type'          => 'Locator Type',
            'attribute_category'    => 'Attribute Category',
            'sub_inventory_group'   => 'Sub Inventory Group',
            'created_at'            => 'Created At',
            'updated_at'            => 'Updated at',
            'deleted_at'            => 'Deleted at',
        ],
    ],
    'uom'         => [
    'title'         => 'Unit of Measurement',
    'title_singular' => 'Unit of Measurement',
    'fields'        => [
            'id'                    => 'ID',
            'uom_code'              => 'UOM Code',
            'uom_name'              => 'UOM Name',
            'description'           => 'Description',
            'attribute1'            => 'Attribute',
            'created_at'            => 'Created At',
            'updated_at'            => 'Updated at',
            'deleted_at'            => 'Deleted at',
        ],
    ],
    'materialTrnTypes'         => [
        'title'          => 'Material Transaction types',
        'title_singular' => 'Material Transaction type',
        'fields'         => [
            'trx_code'          => 'Transaction Code',
            'trx_type'          => 'Transaction Types',
            'trx_action'        => 'Transaction Actions',
            'trx_source_types'  => 'Transaction Source Types',
            'created_at'        => 'Created at',
            'created_at_helper' => '',
            'updated_at'        => 'Updated At',
            'updated_at_helper' => '',
            'deleted_at'        => 'Deleted At',
            'deleted_at_helper' => '',
        ],
    ],

    // add by shindi 07-05-2022
    'trx'         => [
        'title'         => 'Material Transaction',
        'title_singular' => 'Material Transaction',
        'fields'        => [
            'id'                    => 'ID',
            'item'                  => 'Item',
            'description'           => 'Description',
            'subinventory_code'    => 'Sub Inventory Code',
            'subinventory_to'           => 'Sub Inventory To',
            'transaction_quantity'            => 'Transaction Quantity',
            'transaction_uom'            => 'Transaction Uom',
            'transaction_reference'            => 'Transaction Reference',
            'transaction_type_id'   => 'Transaction Type',
            'receiving_document'            => 'Receiving Document',
            'attribute_category'            => 'Attribute Category',
            'transaction_date'            => 'Transaction date',
            'transaction_source_name'   => 'Transaction Source Name',
            'account'            => 'Account',
            'created_at'            => 'Created At',
            'updated_at'            => 'Updated at',
            'deleted_at'            => 'Deleted at',
        ],
    ],

    //add by shindi 09-05-22
    'trx-statuses'         => [
        'title'         => 'Transaction Statuses',
        'title_singular' => 'Transaction Statuses',
        'fields'        => [
            'id'                    => 'ID',
            'trx_code'              => 'Transaction Code',
            'trx_name'              => 'Transaction Name',
            'trx_function'           => 'Transaction Function',
            'created_by'            => 'Created By',
            'updated_by'            => 'Updated By',
            'created_at'            => 'Created At',
            'updated_at'            => 'Updated at',
            'deleted_at'            => 'Deleted at',
        ],
    ],

    'requisition'          => [
        'title'          => 'Purchase Requisition',
        'title_singular' => 'Purchase Requisition',
        'fields'         => [
            'id'                    => 'ID',
            'number'                => 'Number',
            'item'                  => 'item Number',
            'description'           => 'description',
            'quantity'           	=> 'Quantity',
            'price'                 => 'Price',
			'line'                 => 'Line',
            'id_helper'             => '',
            'requested'             => 'Requested By',
            'creation_date'         => 'Creation Date ',
            'Receive'  			    => 'Receive At',
            'cost_center'  			=> 'Cost Center',
            'start_date'            => 'From ',
            'end_date'              => 'To',
            'status'                => 'Status',
            'customer_name_helper'  => '',
            'effective_date'        => 'Effective Date',
            'customer_email_helper' => '',
            'site'                  => 'Site',
            'products_helper'       => '',
            'created_at'            => 'Created At',
            'created_at_helper'     => '',
            'updated_at'            => 'Updated at',
            'updated_at_helper'     => '',
            'deleted_at'            => 'Deleted at',
            'deleted_at_helper'     => '',
            'currency'              => 'Currency',
        ],
    ],

    // Added by shindi 10 Mei 2022
    'report'         => [
        'title'         => 'Standard Reports',
        'title_singular' => 'Unit of Measurement',
        'fields'        => [
            'id'                    => 'ID',
            'uom_code'              => 'UOM Code',
            'uom_name'              => 'UOM Name',
            'description'           => 'Description',
            'attribute1'            => 'Attribute',
            'created_at'            => 'Created At',
            'updated_at'            => 'Updated at',
            'deleted_at'            => 'Deleted at',
        ],
    ],

    //Added by shindi 16/06/2022
    'physic'         => [
        'title'         => 'Physical Inventory',
        'title_singular' => 'Physical Inventory',
        'fields'        => [
            'id'                    => 'ID',
            'item'              => 'Item',
            'uom'              => 'UOM',
            'qty'              => 'Quantity',
            'subinventory_code'    => 'Sub Inventory',
            'locator'    => 'Locator',
            'revision'              => 'Revision',
            'subinv_from'           => 'Sub Inventory  To',
            'subinv_to'             => 'Sub Inventory  From',
            'date'                  => 'Transaction date',
            'rev'                   => 'Rev',
            'attribute1'            => 'Attribute',
            'created_at'            => 'Created At',
            'updated_at'            => 'Updated at',
            'deleted_at'            => 'Deleted at',
        ],
      ],
      'prod'         => [
          'title'          => 'Manufacturing',
          'title_singular' => 'Manufacturing',
          'operation'      => 'Operation',
          'planning'       => 'Planning',
          'bom'            => 'Bill Of Material',
          'wo'            => 'Work Order',
          'fields'         => [
              'id'                    => 'ID',
              'sub_inventory_name'    => 'Subinventory Name',
              'description'           => 'Description',
              'locator_type'          => 'Locator Type',
              'attribute_category'    => 'Attribute Category',
              'sub_inventory_group'   => 'Subinventory Group',
              'created_at'            => 'Created At',
              'updated_at'            => 'Updated at',
              'deleted_at'            => 'Deleted at',
          ],
      ],
      'bom'         => [
          'title'          => 'Bill Of Material',
          'title_singular' => 'Bill Of Material',
          'fields'         => [
              'parent_item'           => 'Parent Item',
              'parent_item_type'    => 'Parent Item Type',
              'child_item'           => 'Child Item',
              'child_item_type'    => 'Child Item Type',
            'id_helper'             => '',
            'requested'             => 'Requested By',
            'creation_date'         => 'Creation Date ',
            'Receive'  			    => 'Receive At',
            'cost_center'  			=> 'Cost Center',
            'start_date'            => 'From ',
            'end_date'              => 'To',
            'status'                => 'Status',
            'customer_name_helper'  => '',
            'effective_date'        => 'Effective Date',
            'customer_email_helper' => '',
            'site'                  => 'Site',
            'products_helper'       => '',
            'created_at'            => 'Created At',
            'created_at_helper'     => '',
            'updated_at'            => 'Updated at',
            'updated_at_helper'     => '',
            'deleted_at'            => 'Deleted at',
            'deleted_at_helper'     => '',
            'currency'              => 'Currency',
        ],
    ],

    // Added by shindi 10 Mei 2022
    'report'         => [
        'title'         => 'Standard Reports',
        'title_singular' => 'Unit of Measurement',
        'fields'        => [
            'id'                    => 'ID',
            'uom_code'              => 'UOM Code',
            'uom_name'              => 'UOM Name',
            'description'           => 'Description',
            'attribute1'            => 'Attribute',
            'created_at'            => 'Created At',
            'updated_at'            => 'Updated at',
            'deleted_at'            => 'Deleted at',
        ],
    ],

    //Added by shindi 16/06/2022
    'physic'         => [
        'title'         => 'Physical Inventory',
        'title_singular' => 'Physical Inventory',
        'fields'        => [
            'id'                    => 'ID',
            'item'              => 'Item',
            'uom'              => 'UOM',
            'qty'              => 'Quantity',
            'subinventory_code'    => 'Sub Inventory',
            'locator'    => 'Locator',
            'revision'    => 'Revision',
            'subinv_from'         => 'Sub Inventory  To',
            'subinv_to'           => 'Sub Inventory  From',
            'date'    => 'Transaction date',
            'rev'           => 'Rev',
            'attribute1'            => 'Attribute',
            'created_at'            => 'Created At',
            'updated_at'            => 'Updated at',
            'deleted_at'            => 'Deleted at',
        ],
      ],
      'prod'         => [
          'title'          => 'Manufacturing',
          'title_singular' => 'Manufacturing',
          'operation'      => 'Operation',
          'planning'       => 'Planning',
          'bom'            => 'Bill Of Material',
          'wo'            => 'Work Order',
          'fields'         => [
              'id'                    => 'ID',
              'sub_inventory_name'    => 'Subinventory Name',
              'description'           => 'Description',
              'locator_type'          => 'Locator Type',
              'attribute_category'    => 'Attribute Category',
              'sub_inventory_group'   => 'Subinventory Group',
              'created_at'            => 'Created At',
              'updated_at'            => 'Updated at',
              'deleted_at'            => 'Deleted at',
          ],
      ],
      'bom'         => [
          'title'          => 'Bill Of Material',
          'title_singular' => 'Bill Of Material',
          'fields'         => [
              'parent_item'             =>'Parent Item',
              'parent_item_type'        =>'Parent Item Type',
              'child_item'              =>'Child Item',
              'child_item_type'         => 'Child Item Type',
              'child_item_uom'          => 'Child Item Uom',
              'usage'                   => 'Usage',
              'cost'                    => 'Cost',
              'created_at'            => 'Created At',
              'updated_at'            => 'Updated at',
              'deleted_at'            => 'Deleted at',
              'action'                =>'Action',
          ],
      ],


    'purchaseorder'            => [
        'item_master'            => 'Item Master',
        'org_item'               => 'Organization Item',
        'title_singular'         => 'Item Master',
        'quotation'              => 'Quotation',
		'cr'                     => 'Auto Create',
        'pr'                     => 'Purchase Requisition',
        'po'                     => 'Purchase Order',
        'receive'                => 'Receiving',
        'return'                 => 'Return',
        'supplier'               => 'Supplier',
        'report'                 => 'Purchase Report',
        'fields'               => [
          'item_code'       => 'Item Code',
			'rate_date'		  =>'Rate Date',
            'description'     => 'Description',
            'qty'             => 'QTY',
            'qtyrcv'             => 'QTY Receipt',
            'uom'             => 'Primary UOM',
            'suom'            => 'Secondary UOM',
            'location'        =>'Location',
            'price'           =>'Price',
            'ref'             =>'   Reference Items',
			'currency'       => 'Currency',
			'status'         => 'Status',
			'buyer'   	      => 'Buyer',
            'id_helper'       => '',
            'item_code'        => 'Item Code',
			'rate_date'		   =>'Rate Date',
            'description'      => 'Description',
            'qty'              => 'QTY',
            'qtyrcv'           => 'QTY Receipt',
            'uom'              => 'Primary UOM',
            'suom'             => 'Secondary UOM',
            'location'         =>'Location',
            'price'            =>'Price',
            'ref'              =>'Reference Items',
			'currency'         => 'Currency',
			'status'           => 'Status',
			'buyer'   	       => 'Buyer',
            'id_helper'        => '',
      ],
    ],
    'aPayable'         => [
        'title'         => 'Accounts Payable',
        'title_singular' => 'Accounts Payable',
        'fields'        => [
                'invoice'               => 'AP-01 Invoice',
                'creditmemo'            => 'AP-02 Credit Memo',
                'payment'               => 'AP-03 Payment',
                'No'                    => 'Voucher No',
                'vendor'                => 'Vendor',
                'invoicedate'           => 'Invoice Date',
                'amount'                => 'Amount',
                'type'                  => 'Type',
                'terms'                 => 'Terms',
                'duedate'               => 'Due Date',
                'reference'             => 'reference',
                'invoiceno'             => 'Invoice Number',
                'paymentmethod'         => 'Payment Method',
                'tax'                   => 'Tax',
                'gldate'                => 'GL Date',
                'curr'                  => 'Currency',
                'totalamount'           => 'Total',
                'status'                => 'Status',
                'description'           => 'Description',
                'attribute1'            => 'Attribute',
                'created_at'            => 'Created At',
                'updated_at'            => 'Updated at',
                'deleted_at'            => 'Deleted at',
            ],
        ],
  'table'                     => [
            'wonum'                 => 'WO Number',
            'invitem'               => 'Inventory Item',
            'uomcod'                => 'UOM Code',
            'type'                  => 'Item Type',
            'needdate'              => 'Need By Date',
            'crtby'                 => 'Created by',
            'status'                => 'Status',
            'action'                =>'Action',
        ],


    'aReceivable'               => [
        'title'                 => 'Accounts Receivable',
        'title_singular'        => 'AR - Receivable',
        'cal'                   => 'AR - Calendar',
        'auto'                  => 'AR - Auto Invoice',
        'cust_trans'            => 'AR - Customer Transaction',
        'fields'        => [
                'id'                    => 'ID',
                'uom_code'              => 'UOM Code',
                'uom_name'              => 'UOM Name',
                'description'           => 'Description',
                'attribute1'            => 'Attribute',
                'created_at'            => 'Created At',
                'updated_at'            => 'Updated at',
                'deleted_at'            => 'Deleted at',
            ],
        'ar_calendar'   => [
                'id'                    => 'ID',
                'name'                  => 'Name',
                'status'                => 'Status',
                'num'                   => 'Num',
                'year'                  => 'Year',
                'quarter'               => 'Quarter',
                'from'                  => 'From',
                'to'                    => 'To',
                'created_at'            => 'Created At',
                'updated_at'            => 'Updated at',
                'deleted_at'            => 'Deleted at',
            ],
        'ar' =>[
                'id'                    => 'ID',
                'trx_number'            => 'Number',
                'trx_date'              => 'Trans Date',
                'bill_to'               => 'Customer',
                'term_id'               => 'Term',
                'currency'              => 'Currency Code',
                'delivery_id'           => 'Delivery Num',
                'surat_jalan'           => 'Surat Jalan',
                'delivery_method'       => 'Delivery Method',
                'ship_to'               => 'Ship To',
                'No'                    => 'Voucher No',
                'invoicedate'           => 'Invoice Date',
                'amount'                => 'Amount',
                'type'                  => 'Type',
                'terms'                 => 'Terms',
                'duedate'               => 'Due Date',
                'reference'             => 'reference',
                'invoiceno'             => 'Invoice Number',
                'paymentmethod'         => 'Payment Method',
                'tax'                   => 'Tax',
                'gldate'                => 'GL Date',
                'curr'                  => 'Currency',
                'totalamount'           => 'Total',
                'status'                => 'Status',
                'description'           => 'Description',
                'attribute1'            => 'Attribute',
                'created_at'            => 'Created At',
                'updated_at'            => 'Updated at',
                'deleted_at'            => 'Deleted at',
            ]
        ],

    'workorder'                     => [
        'title'                     => 'Work Order',
        'fields'                    => [
            'parent_item'           => 'Parent Item',
            'parent_item_type'      => 'Parent Item Type',
            'child_item'            => 'Child Item',
            'child_item_type'       => 'Child Item Type',
            'child_item_uom'        => 'Child Item Uom',
            'usage'                 => 'Usage',
            'cost'                  => 'Cost',
            'created_at'            => 'Created At',
            'updated_at'            => 'Updated at',
            'deleted_at'            => 'Deleted at',
            'action'                =>'Action',
        ],
        'table'                     => [
            'wonum'                 => 'WO Number',
            'invitem'               => 'Inventory Item',
            'uomcod'                => 'UOM Code',
            'type'                  => 'Item Type',
            'needdate'              => 'Need By Date',
            'crtby'                 => 'Created by',
            'status'                => 'Status',
            'action'                =>'Action',
        ],
    ],
    'inventory'           => [
        'title'           => 'Inventory',
        'subinventory'    => 'Subinventory',
        'title_singular'  => 'Onhand',
        'transfer'        => 'Subinventory Transfer',
        'mtltrx'        => 'Material Transactions',
        'missTransaction' => 'Miscellaneous',
        'onhand'          => 'Onhand',
        'quick_ship'      => 'Quick Ship',
        'price_list'      => 'Price List',
        'customer'        => 'Customer',
        'post_invoic'     => 'Auto Invoice',
                'fields'         => [
                'id'           => 'ID',
                'item_number'     => 'Item Number',
                'description'     => 'Description',
                'location'       => 'Fix Loc',
                'subinventory'    => 'Subinventory',
                'qty'             => 'Onhand QTY',
                'category'             => 'Category',
        'creation_date'           => 'Creation Date',
        'updated_at'              => 'Updated At',
        ],
        'reports'        => [
            'month'       => 'Month',
            'income'      => 'Income',
            'expenses'    => 'Expenses',
            'fees'        => 'Fees',
            'total'       => 'Total',
            'allProjects' => 'All projects',
        ],
    ],
];
