<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateRaCustomerTrxAllTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('bm_ra_customer_trx_all', function (Blueprint $table) {
            $table->id();
            $table->integer('customer_trx_id')->nullable();
            $table->float('src_invoicing_rule_id')->nullable();
            $table->string('bill_template_name',240)->nullable();
            $table->string('requires_manual_scheduling',1)->nullable();
            $table->string('intercompany_flag',1)->nullable();
            $table->datetime('last_update_date')->nullable();
            $table->string('last_updated_by',64)->nullable();
            $table->string('created_by',64)->nullable();
            $table->string('last_update_login',32)->nullable();
            $table->string('trx_number',20)->nullable();
            $table->DATE('trx_date')->nullable();
            $table->integer('set_of_books_id')->nullable();
            $table->integer('bill_to_contact_id')->nullable();
            $table->integer('batch_id')->nullable();
            $table->string('reason_code',30)->nullable();
            $table->integer('sold_to_customer_id')->nullable();
            $table->integer('sold_to_contact_id')->nullable();
            $table->integer('sold_to_site_use_id')->nullable();
            $table->integer('bill_to_customer_id')->nullable();
            $table->integer('bill_to_site_use_id')->nullable();
            $table->integer('ship_to_customer_id')->nullable();
            $table->integer('ship_to_contact_id')->nullable();
            $table->integer('ship_to_site_use_id')->nullable();
            $table->float('shipment_id')->nullable();
            $table->float('remit_to_address_id')->nullable();
            $table->float('term_id')->nullable();
            $table->DATE('term_due_date')->nullable();
            $table->float('previous_customer_trx_id')->nullable();
            $table->DATE('printing_original_date')->nullable();
            $table->DATE('printing_last_printed')->nullable();
            $table->string('printing_option',20)->nullable();
            $table->float('printing_count')->nullable();
            $table->string('printing_pending',1)->nullable();
            $table->string('purchase_order',50)->nullable();
            $table->string('purchase_order_revision',50)->nullable();
            $table->DATE('purchase_order_date')->nullable();
            $table->string('customer_reference',30)->nullable();
            $table->DATE('customer_reference_date')->nullable();
            $table->string('comments',200)->nullable();
            $table->string('internal_notes',240)->nullable();
            $table->string('exchange_rate_type',30)->nullable();
            $table->DATE('exchange_date')->nullable();
            $table->float('exchange_rate')->nullable();
            $table->float('territory_id')->nullable();
            $table->string('invoice_currency_code',15)->nullable();
            $table->float('initial_customer_trx_id')->nullable();
            $table->float('agreement_id')->nullable();
            $table->DATE('end_date_commitment')->nullable();
            $table->DATE('start_date_commitment')->nullable();
            $table->float('last_printed_sequence_num')->nullable();
            $table->string('attribute_category',30)->nullable();
            $table->string('attribute1',150)->nullable();
            $table->string('attribute2',150)->nullable();
            $table->string('orig_system_batch_name',40)->nullable();
            $table->float('post_request_id')->nullable();
            $table->float('request_id')->nullable();
            $table->float('program_application_id')->nullable();
            $table->float('program_id')->nullable();
            $table->DATE('program_update_date')->nullable();
            $table->string('finance_charges',1)->nullable();
            $table->string('complete_flag',1)->nullable();
            $table->float('posting_control_id')->nullable();
            $table->float('bill_to_address_id')->nullable();
            $table->float('ra_post_loop_number')->nullable();
            $table->float('ship_to_address_id')->nullable();
            $table->string('credit_method_for_rules',30)->nullable();
            $table->string('credit_method_for_installments',30)->nullable();
            $table->float('receipt_method_id')->nullable();
            $table->float('related_customer_trx_id')->nullable();
            $table->float('invoicing_rule_id')->nullable();
            $table->string('ship_via',30)->nullable();
            $table->DATE('ship_date_actual')->nullable();
            $table->string('waybill_number',50)->nullable();
            $table->string('fob_point',30)->nullable();
            $table->float('customer_bank_account_id')->nullable();
            $table->string('interface_header_attribute1',30)->nullable();
            $table->string('interface_header_attribute2',30)->nullable();
            $table->string('interface_header_context',30)->nullable();
            $table->string('default_ussgl_trx_code_context',30)->nullable();
            $table->string('default_ussgl_transaction_code',30)->nullable();
            $table->string('recurred_from_trx_number',20)->nullable();
            $table->string('status_trx',30)->nullable();
            $table->float('doc_sequence_id')->nullable();
            $table->float('doc_sequence_value')->nullable();
            $table->float('paying_customer_id')->nullable();
            $table->float('paying_site_use_id')->nullable();
            $table->string('default_tax_exempt_flag',1)->nullable();
            $table->string('created_from',30)->nullable();
            $table->float('org_id')->nullable();
            $table->DATE('wh_update_date')->nullable();
            $table->string('global_attribute1',140)->nullable();
            $table->string('global_attribute_category',30)->nullable();
            $table->string('edi_processed_flag',1)->nullable();
            $table->string('edi_processed_status',10)->nullable();
            $table->float('global_attribute_number1')->nullable();
            $table->float('global_attribute_number3')->nullable();
            $table->DATE('global_attribute_date2')->nullable();
            $table->string('mrc_exchange_rate_type',140)->nullable();
            $table->string('mrc_exchange_date',140)->nullable();
            $table->string('mrc_exchange_rate',140)->nullable();
            $table->string('payment_server_order_num',80)->nullable();
            $table->string('approval_code',80)->nullable();
            $table->string('address_verification_code',80)->nullable();
            $table->string('old_trx_number',20)->nullable();
            $table->float('br_amount')->nullable();
            $table->string('br_unpaid_flag',1)->nullable();
            $table->string('br_on_hold_flag',1)->nullable();
            $table->float('drawee_id')->nullable();
            $table->float('drawee_contact_id')->nullable();
            $table->float('drawee_site_use_id')->nullable();
            $table->float('remittance_bank_account_id')->nullable();
            $table->string('override_remit_account_flag',1)->nullable();
            $table->float('drawee_bank_account_id')->nullable();
            $table->string('special_instructions',240)->nullable();
            $table->float('remittance_batch_id')->nullable();
            $table->string('prepayment_flag',1)->nullable();
            $table->string('ct_reference',30)->nullable();
            $table->float('contract_id')->nullable();
            $table->float('bill_template_id')->nullable();
            $table->float('reversed_cash_receipt_id')->nullable();
            $table->string('cc_error_code',80)->nullable();
            $table->string('cc_error_text',255)->nullable();
            $table->string('cc_error_flag',1)->nullable();
            $table->string('upgrade_method',30)->nullable();
            $table->float('legal_entity_id')->nullable();
            $table->float('remit_bank_acct_use_id')->nullable();
            $table->float('payment_trxn_extension_id')->nullable();
            $table->float('application_id')->nullable();
            $table->string('payment_attributes',140)->nullable();
            $table->DATE('billing_date')->nullable();
            $table->float('interest_header_id')->nullable();
            $table->string('late_charges_assessed',30)->nullable();
            $table->float('cust_trx_type_seq_id')->nullable();
            $table->float('batch_source_seq_id')->nullable();
            $table->float('related_batch_source_seq_id')->nullable();
            $table->float('primary_resource_salesrep_id')->nullable();
            $table->float('object_version_number')->nullable();
            $table->float('remit_to_address_seq_id')->nullable();
            $table->string('default_taxation_country',2)->nullable();
            $table->string('document_sub_type',140)->nullable();
            $table->string('trx_business_category',140)->nullable();
            $table->string('user_defined_fisc_class',30)->nullable();
            $table->float('source_document_id')->nullable();
            $table->string('source_document_type',140)->nullable();
            $table->string('trx_class',20)->nullable();
            $table->float('first_pty_reg_id')->nullable();
            $table->float('third_pty_reg_id')->nullable();
            $table->string('delivery_method_code',30)->nullable();
            $table->float('print_request_id')->nullable();
            $table->float('ship_to_party_id')->nullable();
            $table->float('ship_to_party_contact_id')->nullable();
            $table->float('ship_to_party_site_use_id')->nullable();
            $table->float('ship_to_party_address_id')->nullable();
            $table->float('sold_to_party_id')->nullable();
            $table->float('document_type_id')->nullable();
            $table->DATE('document_creation_date')->nullable();
            $table->string('rev_rec_application',30)->nullable();
            $table->float('billing_ext_request_id')->nullable();
            $table->float('bill_plan_id')->nullable();
            $table->float('bill_plan_period')->nullable();
            $table->string('ready_for_xml_delivery_flag',1)->nullable();
            $table->string('structured_payment_reference',140)->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ra_customer_trx_all');
    }
}
