<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateRCVHeaderDetTable extends Migration
{
    public function up()
    {
        Schema::create('bm_c_rcv_transactions_id', function (Blueprint $table) {
			$table->increments('id');
            $table->integer('shipment_line_id')->nullable();
			$table->string('created_by',64)->nullable();
			$table->string('last_update_login',32)->nullable();
			$table->integer('shipment_header_id')->nullable();
			$table->integer('line_num')->nullable();
			$table->integer('category_id')->nullable();
			$table->integer('quantity_shipped')->nullable();
			$table->integer('quantity_received')->nullable();
			$table->integer('quantity_delivered')->nullable();
			$table->integer('quantity_returned')->nullable();
			$table->integer('quantity_accepted')->nullable();
			$table->integer('quantity_rejected')->nullable();
			$table->string('uom_code',3)->nullable();
			$table->string('item_description',170)->nullable();
			$table->integer('item_id')->nullable();
			$table->string('item_revision',18)->nullable();
			$table->string('vendor_item_num',75)->nullable();
			$table->string('vendor_lot_num',30)->nullable();
			$table->integer('uom_conversion_rate')->nullable();
			$table->string('shipment_line_status_code',25)->nullable();
			$table->string('source_document_code',25)->nullable();
			$table->integer('po_header_id')->nullable();
			$table->integer('po_line_id')->nullable();
			$table->integer('po_line_location_id')->nullable();
			$table->integer('po_distribution_id')->nullable();
			$table->integer('requisition_line_id')->nullable();
			$table->integer('req_distribution_id')->nullable();
			$table->integer('routing_header_id')->nullable();
			$table->string('packing_slip',25)->nullable();
			$table->integer('from_organization_id')->nullable();
			$table->integer('deliver_to_person_id')->nullable();
			$table->integer('employee_id')->nullable();
			$table->string('destination_type_code',25)->nullable();
			$table->integer('to_organization_id')->nullable();
			$table->string('to_subinventory',10)->nullable();
			$table->integer('deliver_to_location_id')->nullable();
			$table->integer('shipment_unit_price')->nullable();
			$table->integer('transfer_cost')->nullable();
			$table->integer('transportation_cost')->nullable();
			$table->string('attribute1',50)->nullable();
			$table->string('attribute2',50)->nullable();
			$table->integer('attribute_integer1')->nullable();
			$table->DATE('attribute_date1')->nullable();
			$table->DATE('attribute_date2')->nullable();
			$table->DATE('attribute_date3')->nullable();
			$table->DATE('attribute_date4')->nullable();
			$table->DATE('attribute_date5')->nullable();
			$table->datetime('attribute_datetime1')->nullable();
			$table->integer('reason_id')->nullable();
			$table->string('government_context',30)->nullable();
			$table->integer('request_id')->nullable();
			$table->string('destination_context',30)->nullable();
			$table->string('primary_uom_code',3)->nullable();
			$table->string('tax_name',15)->nullable();
			$table->integer('tax_amount')->nullable();
			$table->string('invoice_status_code',25)->nullable();
			$table->string('container_num',35)->nullable();
			$table->integer('transfer_percentage')->nullable();
			$table->integer('ship_to_location_id')->nullable();
			$table->string('country_of_origin_code',2)->nullable();
			$table->string('customer_item_num',50)->nullable();
			$table->integer('secondary_quantity_shipped')->nullable();
			$table->integer('secondary_quantity_received')->nullable();
			$table->string('secondary_uom_code',3)->nullable();
			$table->integer('amount')->nullable();
			$table->integer('amount_received')->nullable();
			$table->integer('job_id')->nullable();
			$table->integer('requested_amount')->nullable();
			$table->integer('material_stored_amount')->nullable();
			$table->string('approval_status',25)->nullable();
			$table->integer('amount_shipped')->nullable();
			$table->integer('receipt_advice_header_id')->nullable();
			$table->integer('customer_id')->nullable();
			$table->integer('customer_site_id')->nullable();
			$table->string('ra_last_action_code',25)->nullable();
			$table->string('trx_business_category',20)->nullable();
			$table->string('tax_invoice_integer',20)->nullable();
			$table->DATE('tax_invoice_date')->nullable();
			$table->string('tax_classification_code',50)->nullable();
			$table->string('product_type',50)->nullable();
			$table->string('product_category',50)->nullable();
			$table->integer('final_discharge_location_id')->nullable();
			$table->integer('customer_item_id')->nullable();
			$table->integer('eway_bill_integer')->nullable();
			$table->DATE('eway_bill_date')->nullable();
            $table->timestamps();
            $table->softDeletes();
        });
    }
}
