<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Traits\LogsActivity;

class ArReceivableApplications extends Model
{
    use HasFactory;
    use SoftDeletes;

    public $table = 'bm_ar_receivable_applications_all';
    protected $dates = [
        'date_requested',
        'date_scheduled',
        'conversion_date',
        'created_at',
        'updated_at',
        // 'deleted_at',
    ];

    protected $fillable = [
        'id',
        'receivable_application_id',
        'exception_reason_code',
        'last_updated_by',
        'last_update_date',
        'created_by',
        'creation_date',
        'amount_applied',
        'amount_applied_from',
        'trans_to_receipt_rate',
        'gl_date',
        'code_combination_id',
        'set_of_books_id',
        'display',
        'apply_date',
        'application_type',
        'status',
        'payment_schedule_id',
        'last_update_login',
        'cash_receipt_id',
        'applied_customer_trx_id',
        'applied_customer_trx_line_id',
        'applied_payment_schedule_id',
        'customer_trx_id',
        'line_applied',
        'tax_applied',
        'freight_applied',
        'receivables_charges_applied',
        'earned_discount_taken',
        'unearned_discount_taken',
        'days_late',
        'application_rule',
        'gl_posted_date',
        'comments',
        'attribute_category',
        'attribute1',
        'attribute2',
        'postable',
        'posting_control_id',
        'acctd_amount_applied_from',
        'acctd_amount_applied_to',
        'acctd_earned_discount_taken',
        'confirmed_flag',
        'program_application_id',
        'program_id',
        'program_update_date',
        'request_id',
        'ussgl_transaction_code',
        'ussgl_transaction_code_context',
        'earned_discount_ccid',
        'unearned_discount_ccid',
        'acctd_unearned_discount_taken',
        'reversal_gl_date',
        'cash_receipt_history_id',
        'org_id',
        'tax_code',
        'global_attribute1',
        'global_attribute2',
        'global_attribute3',
        'global_attribute_category',
        'cons_inv_id',
        'cons_inv_id_to',
        'rule_set_id',
        'line_ediscounted',
        'tax_ediscounted',
        'freight_ediscounted',
        'charges_ediscounted',
        'line_uediscounted',
        'tax_uediscounted',
        'freight_uediscounted',
        'charges_uediscounted',
        'receivables_trx_id',
        'on_account_customer',
        'edisc_tax_acct_rule',
        'unedisc_tax_acct_rule',
        'link_to_trx_hist_id',
        'link_to_customer_trx_id',
        'application_ref_type',
        'application_ref_id',
        'application_ref_num',
        'chargeback_customer_trx_id',
        'secondary_application_ref_id',
        'payment_set_id',
        'application_ref_reason',
        'customer_reference',
        'customer_reason',
        'applied_rec_app_id',
        'secondary_application_ref_type',
        'secondary_application_ref_num',
        'event_id',
        'upgrade_method',
        'object_version_number',
        'global_attribute_number1',
        'created_at',
        'updated_at'
    ];
}
